tarot_cards = [
    "The Fool: You are on the verge of an unexpected and exciting new adventure. Take a leap of faith",
    "The Magician: Your wishes and desires can be realized through determination and willpower.",
    "The High Priestess: A time for learning and listening to your intuition.",
    "The Empress: Connect with your feminine side through creativity, elegance, sensuality, fertility, and nurturing.",
    "The Emperor: You have to pursue your goals similar to the way that the Emperor does, structured, strategically, and with a lot of perseverance.",
    "The Hierophant: Time to learn the necessary values from a trusted source such as a mentor or a spiritual counselor.",
    "The Lovers: You have major life-changing choices to make or are faced with a dilemma. Temptation is often part of that choice or dilemma.",
    "The Chariot: Overcoming obstacles and achieving your goal through determination, focus, and willpower. You will feel motivated, ambitious, and in control.",
    "Strength: You can obtain true control of a situation, and not simply the power to forcefully impose your will.",
    "The Hermit: Committing to a personal quest for truth can be one of the most rewarding experiences of life.",
    "Wheel of Fortune: A chance to discover more about yourself and to listen to your gut. There is nothing to fear.",
    "Justice: Cause and effect as well as balanced thought and action.",
    "The Hanged Man: Vhe sacrifice of people and things that we would rather hold on to. Accept the loss for the greater good.",
    "Death: There is no new beginning without an ending.",
    "Temperance: Hold back from quick judgment. Resist the temptation to react immediately.",
    "Devil: Redirect your attention away from the satisfaction of desires and toward the things that really matter.",
    "The Tower: Total destruction. Prepare for things to be levelled and dismantled.",
    "The Star: Open your heart, realize your inner strength, and have faith that the best is yet to come.",
    "The Moon: Trust your intuition and push forward, you will receive deliverance from what binds you.",
    "The Sun: Look at the bright side of things and remind ourselves that hard times do not last forever",
    "Judgement: Weigh your actions and see to it that they are in line with your values and beliefs",
    "The World: A long-term project, period of study, or any other major event in your life has come full circle and that you accomplished your goals and aspirations.",
    "Suit of Cups: Water - Bring attention to how you react to your environment.",
    "Suit of Pentacles: Earth - Bring attention to your finances.",
    "Suit of Swords: Air - Bring attention to your communication.",
    "Suit of Wands: Fire - Bring attention to your goals and dreams."
]
